version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prom
    volumes:
      - C:/mediast/updatestack/mountpoints/prom:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "5500:3000"
    volumes:
      - C:/mediast/updatestack/mountpoints/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynetwork
    restart: "unless-stopped"

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql1
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1Test#"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork
    restart: "unless-stopped"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - /home/hvadmin/psdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    networks:
      - mynetwork
    restart: always
    ports:
      - 10000:8080

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: ph@sqlfeatures.com
      PGADMIN_DEFAULT_PASSWORD: Password1Test#
    ports:
      - "5050:80"




networks:
  mynetwork:
    external: true

# Notice we don't define the grafana-data volume here anymore
# as we're using bind mounts for grafana