version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prom
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "5500:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynetwork
    restart: "unless-stopped"

  sql:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      container_name: sql1
      ports:
        - "1433:1433"
      environment:
          SA_PASSWORD: "Password1Test#"
          ACCEPT_EULA: "Y"
      networks:
        - mynetwork
      restart: "unless-stopped"

networks:
  mynetwork:
    external: true

volumes:
  grafana-data:
    driver: local
    
