ssh root@10.10.50.106
scp C:\Users\hvadmin\.ssh\id_rsa.pub root@10.10.50.106:~/.ssh/id_rsa.pub
scp C:\Users\hvadmin\.ssh\id_rsa root@10.10.50.106:~/.ssh/id_rsa
type C:\Users\hvadmin\.ssh\id_rsa.pub | ssh root@10.10.50.106 "cat >> ~/.ssh/authorized_keys"
ssh root@10.10.50.106 "cat  ~/.ssh/authorized_keys"
