version: "3.4"

services:
    sql:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: sql1
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Password1Test#"
            ACCEPT_EULA: "Y"
        networks:
          - mynetwork
        restart: "unless-stopped"

networks:
  mynetwork:
    external: true
